### ISSUE TITLE
bundler installation not found

### ISSUE THREAD

**Issue by bnsv** [tobiassvn/bundler.el#28]
Hi. I want to use bundler package in emacs but it dont recognize my bundler instalation.  If i do bundle via regular terminal it work flawlessly. This is the error report:
```
-*- mode: projectile-rails-server; default-directory: "~/latihan/rubee/anoto/rel604/" -*-
Projectile Rails Server started at Mon Oct 25 00:41:40

bundle exec rails server
Traceback (most recent call last):
	2: from /usr/local/bin/bundle:23:in `<main>'
	1: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/local/lib/site_ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)

Projectile Rails Server exited abnormally with code 1 at Mon Oct 25 00:41:40
```

My installed bundlers in ~/.rbenv/shims/bundler
```
$ gem list bundler
*** LOCAL GEMS ***
bundler (default: 2.2.29, 2.2.20, 2.1.4)
```
I also set this ini my init.el
```
;; https://github.com/purcell/exec-path-from-shell
(when (memq window-system '(mac ns x))
  (exec-path-from-shell-initialize))
(when (daemonp)
  (exec-path-from-shell-initialize))
```

**Comment by bnsv** [comment]
I manage to resolve the bundler.el not recognizing bundler installation by `gem cleanup bundler` so it remove the old versions. now it is recognizing the latest bundler. But still the "projectile-rails" package wont recognize bundler.
